[package]
name = "zk_github_attestation"
type = "bin"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
sha256 = { tag = "v0.2.1", git = "https://github.com/noir-lang/sha256" }
sha512 = { tag = "v0.1.0", git = "https://github.com/zkpassport/sha512" }
ecdsa = { tag = "v0.2.9", git = "https://github.com/zkpassport/noir-ecdsa" }
bignum = { tag = "v0.8.0-2", git = "https://github.com/zkpassport/noir-bignum" }
bigcurve = { tag = "v0.11.0-1", git = "https://github.com/zkpassport/noir_bigcurve" }
