[profile.default]
src = "."
out = "out"
libs = ["lib"]
test = "test"
auto_detect_solc = true
optimizer = true
optimizer_runs = 1
evm_version = "cancun"
fs_permissions = [{ access = "read", path = "test/" }]
